version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      APPID: ${APPID}
      MAP_ENDPOINT: ${MAP_ENDPOINT}
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true
